### ISSUE TITLE
Timing out when accessing tract data

### ISSUE THREAD

**Issue by Makosak** [healthyregions/oepsData#16] opened 2024-10-22 00:24 UTC
```
> tracts19 <- load_oeps(scale="tract", 
+                          year=2018,
+                          geometry=TRUE)
trying URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables//T_Latest.csv'
Error in download.file(file, tmpFile, method = method, mode = "wb", quiet = !showProgress) : 
  cannot open URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables//T_Latest.csv'
In addition: Warning message:
In download.file(file, tmpFile, method = method, mode = "wb", quiet = !showProgress) :
  URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables/T_Latest.csv': Timeout of 60 seconds was reached

> tracts19 <- load_oeps(scale="tract", 
+                          year=2018,
+                          geometry=FALSE)
trying URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables//T_Latest.csv'
Error in download.file(file, tmpFile, method = method, mode = "wb", quiet = !showProgress) : 
  cannot open URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables//T_Latest.csv'
In addition: Warning message:
In download.file(file, tmpFile, method = method, mode = "wb", quiet = !showProgress) :
  URL 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables/T_Latest.csv': Timeout of 60 seconds was reached
> 
```

**Comment by Makosak** [comment] 2024-10-22 00:28
Both of these options work  on their own:

tracts19.read <- read.csv("https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables/T_Latest.csv")


library(data.table)
tracts19.fread <- fread("https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables/T_Latest.csv")

**Comment by bucketteOfIvy** [comment] 2024-10-22 01:30
On the back end, the package [makes the `fread` call above](https://github.com/healthyregions/oepsData/blob/main/R/load_oeps.R#L139), which makes this behavior very interesting and weird. As that `load_oeps` call also works on my system (albeit very slowly), my gut instinct is that this is a networking hiccup of some sort. Does the `load_oeps` call still fail on your end if you retry now (or when you try on different connections)? 

Either way, there is currently no back end logic to help catch and provide useful feedback/error handling of timeouts and networking hiccups in general, so that may end up being a welcome addition to the package (especially if this does turn out to be one).

**Comment by mradamcox** [comment] 2024-10-22 01:30
One strange thing is double slashes near the end of the URL. Not sure it's related but we should get that fixed.

**Comment by mradamcox** [comment] 2024-10-22 15:51
Looks like `fread` can also target gzipped files ([docs](https://www.rdocumentation.org/packages/data.table/versions/1.16.2/topics/fread)), so compressing each CSV is something else we could do to reduce the chance of this timeout happening in the future.

**Comment by mradamcox** [comment] 2024-10-22 21:22
Interestingly, this is happening in the docs build as well:

```
Error in `download.file()`:
! download from 'https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/full_tables//T_2000.csv' failed
```

https://github.com/healthyregions/oepsData/actions/runs/11466984292/job/31909157660

**Comment by mradamcox** [comment] 2024-10-22 22:25
The job completes successfully after I removed the extra slash, for what it's worth. @Makosak can you try this again when you get a chance?

**Comment by mradamcox** [comment] 2024-12-05 20:43
Closing now, I can't reproduce this locally so hopefully the problem has been solved, or was just due to a spotty connection at the outset.

**Closed** 2024-12-05 20:43 UTC
Labels: bug
